import express from 'express';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

dotenv.config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function startServer() {
  const app = express();
  app.use(express.json());

  // API Status Check
  app.get('/api/status', (_req, res) => {
    const key = process.env.GEMINI_API_KEY;
    const hasGeminiKey = Boolean(key && key !== 'MY_GEMINI_API_KEY' && key.trim().length > 0);
    res.json({
      hasGeminiKey,
      geminiModel: 'gemini-3.8-flash-lite-tts',
    });
  });

  // Gemini TTS Route
  app.post('/api/tts/gemini', async (req, res) => {
    try {
      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey || apiKey === 'MY_GEMINI_API_KEY' || !apiKey.trim()) {
        return res.status(400).json({
          error: 'GEMINI_API_KEY is not configured in server environment secrets.',
          code: 'NO_API_KEY',
        });
      }

      const { text, voice = 'Kore', style, language, gender } = req.body;
      if (!text || typeof text !== 'string') {
        return res.status(400).json({ error: 'Text prompt is required.' });
      }

      // Build style instruction with special handling for Kurdish accents and dialects
      let effectiveStyle = style || '';
      if (language === 'kurdish' || language === 'ku' || language === 'ckb') {
        const genderDesc = gender === 'female' ? 'female speaker (Kore/Zephyr)' : 'male speaker (Charon/Puck)';
        effectiveStyle = `Speak in clear, fluent, natural Kurdish with native pronunciation as a ${genderDesc}. ${style || ''}`.trim();
      }

      const ai = new GoogleGenAI({
        apiKey,
        httpOptions: {
          headers: {
            'User-Agent': 'aistudio-build',
          },
        },
      });

      const response = await ai.models.generateContent({
        model: 'gemini-3.8-flash-lite-tts',
        contents: [
          {
            role: 'user',
            parts: [
              {
                text: text.slice(0, 1000),
                ...(effectiveStyle ? { speechMetadata: { style: effectiveStyle } } : {}),
              },
            ],
          },
        ],
        config: {
          responseModalities: ['AUDIO'],
          speechConfig: {
            voiceConfig: {
              prebuiltVoiceConfig: { voiceName: voice },
            },
          },
        },
      });

      const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
      if (!base64Audio) {
        return res.status(500).json({ error: 'No audio generated by Gemini model.' });
      }

      return res.json({
        audioBase64: base64Audio,
        format: 'audio/wav',
        model: 'gemini-3.8-flash-lite-tts',
        voice,
      });
    } catch (err: any) {
      console.error('Gemini TTS error:', err);
      return res.status(500).json({
        error: err.message || 'TTS generation failed',
      });
    }
  });

  // KurdishTTS.com Proxy Route (Supports 20k free chars/mo for Kurdish Sorani & Kurmanji)
  app.post('/api/tts/kurdishtts', async (req, res) => {
    try {
      const { apiKey, text, voice = 'Aland', dialect = 'sorani' } = req.body;
      if (!apiKey || typeof apiKey !== 'string' || !apiKey.trim()) {
        return res.status(400).json({ error: 'KurdishTTS.com API key is required (get free at kurdishtts.com).' });
      }
      if (!text || typeof text !== 'string') {
        return res.status(400).json({ error: 'Text is required.' });
      }

      const response = await fetch('https://www.kurdishtts.com/api/tts-proxy', {
        method: 'POST',
        headers: {
          'x-api-key': apiKey.trim(),
          'Content-Type': 'application/json',
          'Accept': 'audio/mpeg, audio/wav, application/json',
        },
        body: JSON.stringify({
          text: text.slice(0, 1000),
          voice,
          dialect,
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        return res.status(response.status).json({
          error: `KurdishTTS API error (${response.status}): ${errorText}`,
        });
      }

      const contentType = response.headers.get('content-type') || 'audio/mpeg';
      if (contentType.includes('application/json')) {
        const json = await response.json();
        if (json.audioBase64) {
          return res.json({ audioBase64: json.audioBase64, format: json.format || 'audio/mpeg' });
        }
      }

      const arrayBuffer = await response.arrayBuffer();
      const base64Audio = Buffer.from(arrayBuffer).toString('base64');
      return res.json({
        audioBase64: base64Audio,
        format: contentType.includes('wav') ? 'audio/wav' : 'audio/mpeg',
        provider: 'KurdishTTS',
      });
    } catch (err: any) {
      return res.status(500).json({ error: err.message || 'KurdishTTS request failed' });
    }
  });

  // Reliable Instant Kurdish & Multilingual Speech Synthesis (Zero 400 errors)
  app.post(['/api/tts/google-kurdish', '/api/tts/instant-speech'], async (req, res) => {
    try {
      const { text, lang = 'ckb', gender = 'female', dialect = 'sorani' } = req.body;
      if (!text || typeof text !== 'string') {
        return res.status(400).json({ error: 'Text is required.' });
      }

      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey || apiKey === 'MY_GEMINI_API_KEY' || !apiKey.trim()) {
        return res.status(400).json({ error: 'GEMINI_API_KEY is not configured in server environment.' });
      }

      const voice = gender === 'male' ? 'Charon' : 'Kore';
      const isKurdish = lang === 'ckb' || lang === 'ku' || lang === 'kurdish' || dialect === 'sorani' || dialect === 'kurmanji';
      const dialectName = dialect === 'kurmanji' ? 'Kurmanji (Northern Kurdish)' : 'Sorani (Central Kurdish)';
      const style = isKurdish
        ? `Speak in clear, natural ${dialectName} with native pronunciation as a ${gender} speaker.`
        : `Speak in clear, natural English with native pronunciation as a ${gender} speaker.`;

      const ai = new GoogleGenAI({
        apiKey,
        httpOptions: {
          headers: { 'User-Agent': 'aistudio-build' },
        },
      });

      const response = await ai.models.generateContent({
        model: 'gemini-3.8-flash-lite-tts',
        contents: [
          {
            role: 'user',
            parts: [
              {
                text: text.slice(0, 1000),
                speechMetadata: { style },
              },
            ],
          },
        ],
        config: {
          responseModalities: ['AUDIO'],
          speechConfig: {
            voiceConfig: {
              prebuiltVoiceConfig: { voiceName: voice },
            },
          },
        },
      });

      const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
      if (!base64Audio) {
        return res.status(500).json({ error: 'No audio generated by speech model.' });
      }

      return res.json({
        audioBase64: base64Audio,
        format: 'audio/wav',
        model: 'gemini-3.8-flash-lite-tts',
        voice,
        gender,
        provider: 'AI Studio Speech Engine',
      });
    } catch (err: any) {
      console.error('Instant speech error:', err);
      return res.status(500).json({ error: err.message || 'Speech generation failed' });
    }
  });

  // Proxy to test ElevenLabs API key if provided by user in the playground
  app.post('/api/tts/elevenlabs-test', async (req, res) => {
    try {
      const { apiKey, text, voiceId = '21m00Tcm4TlvDq8ikWAM' } = req.body;
      if (!apiKey || typeof apiKey !== 'string' || !apiKey.trim()) {
        return res.status(400).json({ error: 'ElevenLabs API key is required.' });
      }
      if (!text || typeof text !== 'string') {
        return res.status(400).json({ error: 'Text is required.' });
      }

      const response = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`, {
        method: 'POST',
        headers: {
          'xi-api-key': apiKey.trim(),
          'Content-Type': 'application/json',
          'Accept': 'audio/mpeg',
        },
        body: JSON.stringify({
          text: text.slice(0, 500),
          model_id: 'eleven_multilingual_v2',
          voice_settings: {
            stability: 0.5,
            similarity_boost: 0.75,
          },
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        return res.status(response.status).json({
          error: `ElevenLabs error (${response.status}): ${errorText}`,
        });
      }

      const arrayBuffer = await response.arrayBuffer();
      const base64Audio = Buffer.from(arrayBuffer).toString('base64');
      return res.json({
        audioBase64: base64Audio,
        format: 'audio/mpeg',
        provider: 'ElevenLabs',
      });
    } catch (err: any) {
      return res.status(500).json({ error: err.message || 'ElevenLabs request failed' });
    }
  });

  // Serve static in production or attach Vite middlewares in development
  if (process.env.NODE_ENV === 'production') {
    app.use(express.static(path.resolve(__dirname, 'dist')));
    app.get('*', (_req, res) => {
      res.sendFile(path.resolve(__dirname, 'dist/index.html'));
    });
  } else {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  }

  const PORT = Number(process.env.PORT) || 3000;
  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running at http://0.0.0.0:${PORT}`);
  });
}

startServer();
